lst = ['Peach','Grapes','Orange','Mango','Watermelon']
print("Number of elements in list :",len(lst))
print("First element in list:" , lst[0])
print("Last element in list:" , lst[4])
lst.append('Guava')
print('Updated list:', lst)
lst.remove('Peach')
print("Updated list:", lst)
lst.sort()
print('Sorted list:', lst)
lst.pop(1)
print("Updated list:", lst)
lst.reverse()
print("Updated list:", lst)
print("Multiplication on list:", lst*3)